# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login into Remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IPADDRESS }}
          username: ubuntu
          key: ${{ secrets.PRIVATEKEY }}
          port: 22
          script: |
           dir="3Btest"
            if [ -d "$dir" ]; then
                echo "Directory exist"
                cd 3Btest && git pull origin master
            else
                echo "not exist"
                  git clone git@github.com:jhavivek1996/3Btest.git
            fi
            
          
